apiVersion: v1
entries:
  app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-01-12T19:40:07.719126+03:00"
    dependencies:
    - condition: back.enabled
      name: back
      repository: file://./charts/back
      version: 0.1.0
    - condition: postgres.enabled
      name: postgres
      repository: file://./charts/postgres
      version: 0.1.0
    description: Umbrella Helm chart for cat-api application with backend and PostgreSQL
      database
    digest: f688afcdae904d46ce182b55af94a51972ca9401bac12b2057ef47437caf5e59
    name: app
    type: application
    urls:
    - file:///Users/mariakochenkova/Documents/PROJECTS/DevOps/helm/releases/app-0.1.0.tgz
    version: 0.1.0
  back:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-01-12T19:40:07.719421+03:00"
    description: Helm chart for cat-api backend application (FastAPI)
    digest: 896017fc4299ce3041ae4f032a493976bbe7e267190b5a89ea4b1025b06ee38e
    name: back
    type: application
    urls:
    - file:///Users/mariakochenkova/Documents/PROJECTS/DevOps/helm/releases/back-0.1.0.tgz
    version: 0.1.0
  postgres:
  - apiVersion: v2
    appVersion: "15.0"
    created: "2026-01-12T19:40:07.719649+03:00"
    description: Helm chart for PostgreSQL 15 StatefulSet with persistent storage
    digest: 634e029156ec1b770b69e50662f3e8db9cbcf8f015a4aa90612acb4c72a5c312
    name: postgres
    type: application
    urls:
    - file:///Users/mariakochenkova/Documents/PROJECTS/DevOps/helm/releases/postgres-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-12T19:40:07.717723+03:00"
