kind: Secret
apiVersion: v1
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
metadata:
  {{- if and .Values.database.secretRef.name (ne .Values.database.secretRef.name "") }}
  name: {{ .Values.database.secretRef.name }}
  {{- else }}
  name: {{ .Release.Name }}-postgres-secrets
  {{- end }}
type: Opaque