# global:
#   enabled: true
#   tlsDisable: true

# injector:
#   enabled: false


# server:
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     hosts:
#       - host: vault.localhost
#     extraPaths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: vault
#             port:
#               number: 8200
#       - path: /ui
#         pathType: Prefix
#         backend:
#           service:
#             name: vault-ui
#             port:
#               number: 8200

#   standalone:
#     enabled: true
#     config: |
#       ui = true
#       listener "tcp" {
#         address = "[::]:8200"
#         cluster_address = "[::]:8201"
#         tls_disable = "true"
#       }

#       storage "file" {
#         path = "/vault/data"
#       }

# ui:
#   enabled: true
#   serviceType: "NodePort"
# -------

global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault.localhost
        paths: [] # Leave this empty so extraPaths can take over
    extraPaths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-vault
            port:
              number: 8200
      - path: /ui
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-vault-ui
            port:
              number: 8200

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = "true"
      }

      storage "file" {
        path = "/vault/data"
      }

ui:
  enabled: true
  serviceType: "NodePort"
