apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cat-api-ingress
  namespace: cat-api-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 192.168.105.2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cat-api-service
            port:
              number: 8000
