apiVersion: v1
kind: Service
metadata:
  name: cat-api-service
  namespace: cat-api-ns
spec:
  type: ClusterIP
  selector:
    app: cat-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
