apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  PGDATA: "/var/lib/postgresql/data/pgdata"
