apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-pvc
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
{{ toYaml .Values.statefulset.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.statefulset.pvc.storage }}
