apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-service
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{ include "postgres.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}