apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secrets
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | b64enc }}
